# Generated by Django 3.2.3 on 2021-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='words',
            field=models.TextField(null=True),
        ),
    ]
